### ISSUE TITLE
Implement support for a real SCM provider

### ISSUE THREAD

**Issue by atra2396** [atra2396/READUS#2]
# Goal
READUS should be able to read data from at least one real SCM system that lives on the web.

# Details
Azure DevOps would be the most immediately useful to us, but GitHub might be easier to work with. I will let whomever picks this up decide where to begin. I don’t think handling user authentication is necessary for this one - assume an existing record exists for the organization/repository in the storage layer. There is currently an in-memory model for the storage layer, so this should be doable without having a real DBMS yet. This may require changes to the domain objects, which is totally fine.

# Requirements
- At least one project is added that consists of the contracts from the “SourceControl” project implemented.

**Comment by eurubkov** [comment]
@atra2396 For MVP, should we allow users to get readmes from the selected repository, or can we just get them all from all repos across the project for Azure Devops and across the organization for Github? For github, to get all of them across the org all you need is the org name and an auth token. To get them just for a particular repo, you'll also need the username to whom the repo belongs (all github repos have the format of {username}/{repoName}.
For devops we might have to iterate over all the repos though. 

I branched off the AzureDevOps branch and implemented GitHub SCM to get the readmes across all repos. We can discuss the path forward whenever you have time

**Comment by atra2396** [comment]
@eurubkov I would lean toward the latter, collecting as many readmes as we can. The site is more valuable the more documents it contains, so I'd err on the side of over-collecting than under-collecting. We can add the option to exclude documents in the future.
